fix release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -76,14 +76,14 @@ jobs:
         run: csi ./scripts/Release.csx "$GAME" "$PROJECT" "$VERSION_BUMP_TYPE" "$CHANGELOG_DESCRIPTION"
       - name: Build
         run: msbuild /property:Configuration=Release
-      - name: Upload to Thunderstore
-        if: steps.bump_version.outputs.release_thunderstore == 'true'
-        env:
-          GAME: ${{ matrix.changeset.game }}
-          PROJECT: ${{ matrix.changeset.project }}
-          NEW_VERSION: ${{ steps.bump_version.outputs.new_version }}
-          THUNDERSTORE_API_TOKEN: ${{ secrets.THUNDERSTORE_API_TOKEN }}
-        run: csi ./scripts/UploadThunderstore.csx "$GAME" "$PROJECT" "$NEW_VERSION"
+      # - name: Upload to Thunderstore
+      #   if: steps.bump_version.outputs.release_thunderstore == 'true'
+      #   env:
+      #     GAME: ${{ matrix.changeset.game }}
+      #     PROJECT: ${{ matrix.changeset.project }}
+      #     NEW_VERSION: ${{ steps.bump_version.outputs.new_version }}
+      #     THUNDERSTORE_API_TOKEN: ${{ secrets.THUNDERSTORE_API_TOKEN }}
+      #   run: csi ./scripts/UploadThunderstore.csx "$GAME" "$PROJECT" "$NEW_VERSION"
       - name: Copy LiveSplit build for commit
         if: steps.bump_version.outputs.release_livesplit == 'true'
         env:
@@ -103,7 +103,18 @@ jobs:
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git add -A
           git commit -m "Release" --no-verify
-          git push --no-verify
+          for i in {1..3}; do
+            git fetch
+            if ! git rebase --autostash --no-verify; then
+              git rebase --abort
+              echo "Failed to rebase with main, probably due to git conflict. Manual fix required..."
+              exit 1
+            fi
+            if git push --no-verify; then
+              exit 0
+            fi
+          done
+          exit 1
       - name: Create release
         uses: softprops/action-gh-release@v1
         with:
